import type { Metadata } from "next";

import Provider from "@/provider/Provider";

import "./globals.css";

export const metadata: Metadata = {
  title: "Flower shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
